name: Repo visualizer
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update diagram
        uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85
        with:
          output_file: "diagram.svg"
          excluded_paths: "node_modules,dist,.git"
          commit_message: "Repo visualizer: update diagram [skip ci]"
          file_colors: '{"py": "#1982C4", "yaml": "#8AC926", "yml": "#8AC926", "toml": "#6A4C93", "lock": "#6A4C93", "md": "#1982C4", "html": "#FFCA3A", "json": "#8AC926"}'
